// Generated by go-wayland-scanner
// https://github.com/Nomadcxx/sysc-wayland/cmd/sysc-wayland-scanner
// XML file : ../../../protocols/fractional-scale-v1.xml
//
// fractional_scale_v1 Protocol Copyright:
//
// Copyright © 2022 Kenny Levinsen
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package fractionalscale

import "github.com/Nomadcxx/sysc-wayland/client"

// WpFractionalScaleManagerV1InterfaceName is the name of the interface as it appears in the [client.Registry].
// It can be used to match the [client.RegistryGlobalEvent.Interface] in the
// [Registry.SetGlobalHandler] and can be used in [Registry.Bind] if this applies.
const WpFractionalScaleManagerV1InterfaceName = "wp_fractional_scale_manager_v1"

// WpFractionalScaleManagerV1 : fractional surface scale information
//
// A global interface for requesting surfaces to use fractional scales.
type WpFractionalScaleManagerV1 struct {
	client.BaseProxy
}

// NewWpFractionalScaleManagerV1 : fractional surface scale information
//
// A global interface for requesting surfaces to use fractional scales.
func NewWpFractionalScaleManagerV1(ctx *client.Context) *WpFractionalScaleManagerV1 {
	wpFractionalScaleManagerV1 := &WpFractionalScaleManagerV1{}
	ctx.Register(wpFractionalScaleManagerV1)
	return wpFractionalScaleManagerV1
}

// Destroy : unbind the fractional surface scale interface
//
// Informs the server that the client will not be using this protocol
// object anymore. This does not affect any other objects,
// wp_fractional_scale_v1 objects included.
func (i *WpFractionalScaleManagerV1) Destroy() error {
	defer i.MarkZombie()
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetFractionalScale : extend surface interface for scale information
//
// Create an add-on object for the the wl_surface to let the compositor
// request fractional scales. If the given wl_surface already has a
// wp_fractional_scale_v1 object associated, the fractional_scale_exists
// protocol error is raised.
//
//	surface: the surface
func (i *WpFractionalScaleManagerV1) GetFractionalScale(surface *client.Surface) (*WpFractionalScaleV1, error) {
	id := NewWpFractionalScaleV1(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

type WpFractionalScaleManagerV1Error uint32

// WpFractionalScaleManagerV1Error :
const (
	// WpFractionalScaleManagerV1ErrorFractionalScaleExists : the surface already has a fractional_scale object associated
	WpFractionalScaleManagerV1ErrorFractionalScaleExists WpFractionalScaleManagerV1Error = 0
)

func (e WpFractionalScaleManagerV1Error) Name() string {
	switch e {
	case WpFractionalScaleManagerV1ErrorFractionalScaleExists:
		return "fractional_scale_exists"
	default:
		return ""
	}
}

func (e WpFractionalScaleManagerV1Error) Value() string {
	switch e {
	case WpFractionalScaleManagerV1ErrorFractionalScaleExists:
		return "0"
	default:
		return ""
	}
}

func (e WpFractionalScaleManagerV1Error) String() string {
	return e.Name() + "=" + e.Value()
}

// WpFractionalScaleV1InterfaceName is the name of the interface as it appears in the [client.Registry].
// It can be used to match the [client.RegistryGlobalEvent.Interface] in the
// [Registry.SetGlobalHandler] and can be used in [Registry.Bind] if this applies.
const WpFractionalScaleV1InterfaceName = "wp_fractional_scale_v1"

// WpFractionalScaleV1 : fractional scale interface to a wl_surface
//
// An additional interface to a wl_surface object which allows the compositor
// to inform the client of the preferred scale.
type WpFractionalScaleV1 struct {
	client.BaseProxy
	preferredScaleHandler WpFractionalScaleV1PreferredScaleHandlerFunc
}

// NewWpFractionalScaleV1 : fractional scale interface to a wl_surface
//
// An additional interface to a wl_surface object which allows the compositor
// to inform the client of the preferred scale.
func NewWpFractionalScaleV1(ctx *client.Context) *WpFractionalScaleV1 {
	wpFractionalScaleV1 := &WpFractionalScaleV1{}
	ctx.Register(wpFractionalScaleV1)
	return wpFractionalScaleV1
}

// Destroy : remove surface scale information for surface
//
// Destroy the fractional scale object. When this object is destroyed,
// preferred_scale events will no longer be sent.
func (i *WpFractionalScaleV1) Destroy() error {
	defer i.MarkZombie()
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// WpFractionalScaleV1PreferredScaleEvent : notify of new preferred scale
//
// Notification of a new preferred scale for this surface that the
// compositor suggests that the client should use.
//
// The sent scale is the numerator of a fraction with a denominator of 120.
type WpFractionalScaleV1PreferredScaleEvent struct {
	Scale uint32
}
type WpFractionalScaleV1PreferredScaleHandlerFunc func(WpFractionalScaleV1PreferredScaleEvent)

// SetPreferredScaleHandler : sets handler for WpFractionalScaleV1PreferredScaleEvent
func (i *WpFractionalScaleV1) SetPreferredScaleHandler(f WpFractionalScaleV1PreferredScaleHandlerFunc) {
	i.preferredScaleHandler = f
}

func (i *WpFractionalScaleV1) HasFD(opcode uint32) bool {
	return false
}

func (i *WpFractionalScaleV1) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.preferredScaleHandler == nil {
			return
		}
		var e WpFractionalScaleV1PreferredScaleEvent
		l := 0
		e.Scale = client.Uint32(data[l : l+4])
		l += 4

		i.preferredScaleHandler(e)
	default:
		panic("client: unsupported opcode")
	}
}
